#!/bin/bash

############
# Settings #
############
SCREEN_SESSION_NAME="miner"
WALLET_ADDRESS="$1"
LOGFILE="$HOME/.miner-log"
############
CURRENTLY_MINING=false


stop_miner() {
	echo "Stopping miner..."
	screen -S $SCREEN_SESSION_NAME -X stuff "^C"
	CURRENTLY_MINING=false
}

start_miner() {
	#MINING_COMMAND="PhoenixMiner -pool asia1.ethermine.org:4444 -wal "$WALLET_ADDRESS" -worker asus -epsw x -mode 1 -log 0 -mport 0 -etha 0 -ftime 55 -retrydelay 1 -tt 79 -tstop 89  -coin eth"

	# We select two network servers for ethminer, this way it will infinitely retry connections between the two
	# When you utilize a single address it will fail on the first dropped network connection
	MINING_COMMAND="ethminer -P stratum://$WALLET_ADDRESS@asia1.ethermine.org:4444 -P stratum://$WALLET_ADDRESS@eu1.ethermine.org:4444"

	if [[ $CURRENTLY_MINING == true ]]; then
		echo "Mining already active, not starting a second miner"
	else
		echo "Starting miner..."
		screen -dmS "$SCREEN_SESSION_NAME" -L -Logfile "$LOGFILE" $MINING_COMMAND
		CURRENTLY_MINING=true
	fi
dd
}

if [[ ! $WALLET_ADDRESS ]]; then
	echo "You must pass a wallet address to start"
	exit 1
fi

# Cleanup existing screen sessions
sessions="$(screen -list | grep -P '^\s+' | grep -oP '(?<=\d{5}\.).*?(?=\s+)')"
if [[ "$sessions" ]]; then
	for session in $sessions; do
		echo "Found existing screen session '$session'"
		if [[ $session == "$SCREEN_SESSION_NAME" ]]; then
			stop_miner
		fi
	done
fi

dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | while read -r line; do
	echo "New message: $line"
	case "$line" in
	*"boolean true"*)
		echo "Lock screen active..."
		start_miner
		;;
	*"boolean false"*)
		echo "Lock screen inactive..."
		stop_miner
		;;
	esac
done
