#!/bin/bash

############
# Settings #
############
SCREEN_SESSION_NAME="miner"
WALLET_ADDRESS="$1"
LOGFILE="$HOME/.miner-log"
############

currently_mining() {
	screen -ls $SCREEN_SESSION_NAME &>/dev/null
}

stop_miner() {
	if currently_mining; then
		echo "Stopping miner..."
		screen -S $SCREEN_SESSION_NAME -X stuff "^C"
	fi
}

start_miner() {
	#MINING_COMMAND="PhoenixMiner -pool asia1.ethermine.org:4444 -wal "$WALLET_ADDRESS" -worker asus -epsw x -mode 1 -log 0 -mport 0 -etha 0 -ftime 55 -retrydelay 1 -tt 79 -tstop 89  -coin eth"

	# We select two network servers for ethminer, this way it will infinitely retry connections between the two
	# When you utilize a single address it will fail on the first dropped network connection
	MINING_COMMAND="ethminer -P stratum://$WALLET_ADDRESS@asia1.ethermine.org:4444 -P stratum://$WALLET_ADDRESS@eu1.ethermine.org:4444"

	if ! currently_mining; then
		echo "Starting miner..."
		screen -dmS "$SCREEN_SESSION_NAME" -L -Logfile "$LOGFILE" $MINING_COMMAND
	fi
	dd
}

if [[ ! $WALLET_ADDRESS ]]; then
	echo "You must pass a wallet address to start"
	exit 1
fi

# Cleanup existing screen sessions
if currently_mining; then
	stop_miner
fi

previous_active_state=false
while true; do
	current_active_state="$(qdbus org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.GetActive)"
	if [[ $previous_active_state == "false" ]] && [[ $current_active_state == "true" ]]; then
		echo "Lock screen active..."
		start_miner
	elif [[ $previous_active_state == "true" ]] && [[ $current_active_state == "false" ]]; then
		echo "Lock screen inactive..."
		stop_miner
	fi
	previous_active_state="$current_active_state"
	sleep 2
done

# Dbus monitor appears to be kind of flaky under GNOME 40 inside of a systemd service
# dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | while read -r line; do
# 	echo "New message: $line"
# 	case "$line" in
# 	*"boolean true"*)
# 		echo "Lock screen active..."
# 		start_miner
# 		;;
# 	*"boolean false"*)
# 		echo "Lock screen inactive..."
# 		stop_miner
# 		;;
# 	esac
# done
